spring:
    application:
        name: cards
    config:
        #        import: ${DB_CONF},${APP_CONF}
        import: ${CONF_DIR}/${spring.application.name}/config.yaml,${CONF_DIR}/${spring.application.name}/database.yaml